name: comuno
description: Application in Flutter for comuno.org.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.1

environment:
#  sdk: ">=2.0.0-dev.68.0 <3.0.0"
  sdk: '>=1.20.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl:
  intl_translation:

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  google_sign_in:
#  flutter_twitter_login:
  flutter_twitter_login:
    git: git://github.com/vudvhitech/flutter_twitter_login.git
  firebase_auth:
  cloud_firestore: ^0.12.9+4
  rxdart:
  image_picker:
  file_picker:
  firebase_storage:
  location:
  geocoder:
  font_awesome_flutter:
  shared_preferences: ^0.5.3+1
  cached_network_image: ^2.0.0-rc
  image:

  # into slider
  intro_views_flutter:
    git: git@bitbucket.org:bas24/intro_animated.git
  # animated background dependency
  simple_animations: ^1.3.3
  flutter_typeahead:  # ^1.7.0
    git: git://github.com/KaYBlitZ/flutter_typeahead.git
#    git: git@github.com:AbdulRahmanAlHamali/flutter_typeahead.git
  pk_skeleton: ^0.0.2
  timeago: ^2.0.21
  random_string: ^1.1.0
  jiffy: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/comuno_logo.png
    - assets/comuno_icon.png
    - assets/google_icon.jpg
    - assets/Twitter_Logo_Blue.jpg
    - assets/envelope.jpg
    - assets/no_image.png
    - assets/blankimage.png
    - assets/background_def.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
